/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ImportJsonld } from './importJsonld';
import type { ApiImportsGetCollection200HydraSearch } from './apiImportsGetCollection200HydraSearch';
import type { ApiImportsGetCollection200HydraView } from './apiImportsGetCollection200HydraView';

export type ApiImportsGetCollection200 = {
  'hydra:member': ImportJsonld[];
  'hydra:search'?: ApiImportsGetCollection200HydraSearch;
  'hydra:totalItems'?: number;
  'hydra:view'?: ApiImportsGetCollection200HydraView;
};
