/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ApiImportsGetCollection200HydraSearchHydraMappingItem } from './apiImportsGetCollection200HydraSearchHydraMappingItem';

export type ApiImportsGetCollection200HydraSearch = {
  '@type'?: string;
  'hydra:mapping'?: ApiImportsGetCollection200HydraSearchHydraMappingItem[];
  'hydra:template'?: string;
  'hydra:variableRepresentation'?: string;
};
