/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ApiImportsGetCollection200HydraSearchHydraMappingItemProperty } from './apiImportsGetCollection200HydraSearchHydraMappingItemProperty';

export type ApiImportsGetCollection200HydraSearchHydraMappingItem = {
  '@type'?: string;
  property?: ApiImportsGetCollection200HydraSearchHydraMappingItemProperty;
  required?: boolean;
  variable?: string;
};
