/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */

export type ImportJsonldContextOneOfHydra = typeof ImportJsonldContextOneOfHydra[keyof typeof ImportJsonldContextOneOfHydra];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImportJsonldContextOneOfHydra = {
  'http://wwww3org/ns/hydra/core#': 'http://www.w3.org/ns/hydra/core#',
} as const;
