/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ImportJsonldContext } from './importJsonldContext';
import type { ImportJsonldCreatedAt } from './importJsonldCreatedAt';
import type { ImportJsonldFile } from './importJsonldFile';

export interface ImportJsonld {
  readonly '@context'?: ImportJsonldContext;
  readonly '@id'?: string;
  readonly '@type'?: string;
  createdAt?: ImportJsonldCreatedAt;
  file?: ImportJsonldFile;
  readonly id?: number;
  importLabel?: string;
}
