/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ImportJsonldContextOneOf } from './importJsonldContextOneOf';

export type ImportJsonldContext = string | ImportJsonldContextOneOf;
